# Generated by Django 5.1 on 2024-08-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('documento_identidad', models.CharField(max_length=50, unique=True)),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorInvitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('documento_identidad', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEntradaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.BigIntegerField()),
                ('tipo_persona', models.CharField(choices=[('Empleado', 'Empleado'), ('ProveedorInvitado', 'ProveedorInvitado')], max_length=20)),
                ('hora_ingreso', models.DateTimeField()),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('motivo_retiro', models.CharField(blank=True, choices=[('Cita médica', 'Cita médica'), ('Calamidad', 'Calamidad'), ('Diligencia personal', 'Diligencia personal'), ('Otro', 'Otro')], max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
